dependencies:
- name: pipeline-cluster-monitor
  repository: https://kubernetes-charts.banzaicloud.com
  version: '>=0.1.17'
  alias: monitor
  condition: monitor.enabled
- name: pipeline-cluster-ingress
  repository: https://kubernetes-charts.banzaicloud.com
  version: '>=0.0.6'
  alias: ingress
  condition: ingress.enabled
